erDiagram
    CLIENT ||--o{ COMMANDE : passe
    ADMINISTRATEUR ||--o{ VEHICULE : gere
    COMMANDE ||--|{ RESERVATION : contient
    VEHICULE ||--o{ RESERVATION : reserve_dans

    CLIENT {
        int id
        string email
        string motDePasse
        string nom
        string prenom
        date dateObtentionPermis
    }

    ADMINISTRATEUR {
        int id
        string email
        string motDePasse
        string nom
        string prenom
    }

    VEHICULE {
        int id
        string marque
        string modele
        float tarifParJour
    }

    COMMANDE {
        int id
        enum statut
        datetime dateCreation
        string modePaiement
        float TotaleCommande
    }

    RESERVATION {
        int id
        date dateDebut
        date dateFin
        float TotaleReservation
    }